name: Install Python3 and Checkov

# This workflow is triggered manually
on:
  workflow_dispatch:
jobs:
  dev-plan-network:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Install Python3 and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 --version
          pip3 --version

      # Step 3: Install Checkov
      - name: Install Checkov
        run: |
          pip3 install checkov
          checkov --version

      # Step 4: Run Terragrunt Action
      # - name: dev-plan-network
      #   uses: gruntwork-io/terragrunt-action@v2
      #   with:
      #     tf_version: '1.5.7'
      #     tg_version: '0.53.2'
      #     tg_command: 'version'

      - name: dev-plan-network
        continue-on-error: false
        uses: gruntwork-io/terragrunt-action@v2
        env:
          INPUT_PRE_EXEC_1: |
            mise use -g python@'3.12.3'
            mise use -g checkov@'3.2.70'
        with:
          tf_version: '1.5.7'
          tg_version: '0.53.2'
          tg_command: 'version' 

      # Step 2: Update system packages
      - name: Update system packages
        run: |
          sudo apt-get update

      # Step 3: Install Python3 and pip
      - name: Install Python3 and pip
        run: |
          sudo apt-get install -y python3 python3-pip
          python3 --version
          pip3 --version

      # Step 4: Install Checkov
      - name: Install Checkov
        run: |
          pip3 install checkov
          checkov --version
