name: 'pr-helm-airbyte-deploy'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'helm/airbyte/**'

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
      pull-requests: write

jobs:
  dev-helm-check-dryrun:
    runs-on: ubuntu-latest
    steps:  
      - name: 'Checkout'
        uses: actions/checkout@main  

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.8.1
          
      - name: Ensure Helm repo config directory exists
        run: mkdir -p /home/runner/.config/helm/repositories    

      - name: Add Airbyte Helm repo
        run: helm repo add airbyte https://airbytehq.github.io/helm-charts

      - name: Update Helm repos
        run: helm repo update

      - name: Template Airbyte Helm chart
        run: helm template airbyte/airbyte -f helm/airbyte/values.yaml > helm/airbyte/template/k8s-template.yaml

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: helm/airbyte/template/
          quiet: true 
          soft_fail: true 
          framework: kubernetes 
          output_format: sarif 
          skip_check: CKV_K8S_43,CKV_K8S_22,CKV_K8S_40,CKV_K8S_21,CKV_K8S_38,CKV_K8S_35,CKV_K8S_8,CKV_K8S_23,CKV_K8S_14,CKV_K8S_12,CKV_K8S_13,CKV_K8S_10,CKV_K8S_11,CKV_K8S_37,CKV_K8S_31,CKV_K8S_15,CKV_K8S_9,CKV_K8S_30,CKV_K8S_29,CKV_K8S_28,CKV_K8S_20,CKV_K8S_49
          var_file: ./helm/airbyte/values.yaml

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
