name: Install Python3 and Checkov

# This workflow is triggered manually
on:
  workflow_dispatch:

jobs:
  setup-environment:
    name: Install Python3 and Checkov
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository (optional if required)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Update system packages
      - name: Update system packages
        run: |
          sudo apt-get update

      # Step 3: Install Python3 and pip
      - name: Install Python3 and pip
        run: |
          sudo apt-get install -y python3 python3-pip
          python3 --version
          pip3 --version

      # Step 4: Install Checkov
      - name: Install Checkov
        run: |
          pip3 install checkov
          checkov --version
